name: Container Deployment Pipeline
on:
  workflow_dispatch:
jobs:
  calling-workflow-job:
    uses: BrandonTheQA/Fully-Compliant-Pipeline/.github/workflows/workflow.yml@main
    secrets:
             creds: ${{ secrets.AZURE_CREDENTIALS }}
